# fly.toml app configuration file generated for flower-medicine-chat on 2025-08-24T14:52:10Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'flower-medicine-chat'
primary_region = 'bom'

[build]

[[mounts]]
  source = 'chroma'
  destination = '/app/chroma'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
